[workspace]

resolver = "2"

members = ["contract-bindings", "contracts/rust", "sequencer", "utils"]

[workspace.dependencies]
hotshot = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.8" }
hotshot-orchestrator = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.8" }
hotshot-stake-table = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.8" }
hotshot-state-prover = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.8" }
hotshot-task = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.8" }
hotshot-types = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.8" }
hotshot-web-server = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.8" }
hotshot-testing = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.8" }

hotshot-query-service = { git = "https://github.com/EspressoSystems/hotshot-query-service", branch = "main" }
jf-plonk = { git = "https://github.com/EspressoSystems/jellyfish", features = [
  "test-apis",
  "test-srs",
] }
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", features = [
  "std",
  "test-srs",
] }
jf-relation = { git = "https://github.com/EspressoSystems/jellyfish", features = [
  "std",
] }
jf-utils = { git = "https://github.com/EspressoSystems/jellyfish" }
surf-disco = { git = "https://github.com/EspressoSystems/surf-disco", tag = "v0.4.6" }
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco", tag = "v0.4.6" }
trait-variant = "0.1"
bytesize = "1.3"
itertools = "0.12"
rand_chacha = "0.3"
rand_distr = "0.4"
